name: Build APK from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Unzip project
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          unzip -q MealPlanner.zip -d extracted
          echo "Extracted contents:"
          ls -la extracted

      - name: Build debug APK
        working-directory: extracted/GithubMealTester
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: extracted/GithubMealTester/app/build/outputs/apk/debug/*.apk
